### ISSUE TITLE
Esc then b sends me to the beginning of the line

### ISSUE THREAD

**Issue by jeaye** [GermainZ/weechat-vimode#13] opened 2015-02-02 13:21 UTC
I'm running weechat (WeeChat 1.0.1) in tmux (using the escape time of 0) on Arch Linux x64. When I'm in insert mode and I type a couple of words, then hit `ESC b` to go into normal mode and back before the last word, I instead am put into normal mode and my cursor goes to the beginning of the line.

**Comment by jeaye** [comment] 2015-02-02 14:00
With some more testing, I've found that hitting `ESC B` (that is, shift + b) doesn't cause this issue. For now, I'll be using that. Still, something is fishy.

I should note, I *have* run `/vimode bind_keys` and the only change I've made is resetting `ctrl-W` back to its default.

**Comment by GermainZ** [comment] 2015-02-02 18:26
I can't reproduce this. Could you please upload a screencast or give detailed instructions?

**Comment by jeaye** [comment] 2015-02-03 01:19
I've updated to WeeChat 1.1.1 and the issue still exists. After a bit of debugging, I found the issue. Looks like it only happens for grammar Nazis...

0) Start weechat 1.1.1 in tmux (escape time is 0)
1) Type "foo bar spam" (no quotes)
2) `ESC b`
3) Notice this works as expected
4) Delete the line `cc`
5) Now, simulate being jeaye: Type "foo bar spam." (no quotes, note the period)
6) `ESC b`
7) The cusor jumps to the beginning of the line

I have found that this issue happens on multiple punctuation marks, including: `. , !`

Hopefully this helps.

**Comment by GermainZ** [comment] 2015-02-03 10:36
Fixed a long overdue issue which should take care of this as well. See 14397d0aa3c8be9e91f2e78b78868f2eff604da9.

**Comment by GermainZ** [comment] 2015-02-03 11:42
This actually stills happens (e.g. `This is a test!<Space><Esc><b>`).

**Comment by GermainZ** [comment] 2015-02-03 12:44
Fixed in f7f3456.

**Closed by GermainZ** 2015-02-03 12:44 UTC
